### ISSUE TITLE
error 

### ISSUE THREAD

**Issue by aungmoewin** [asticode/go-astiav#1]
Error occurred as follow when demuxing_decoding example is compiled

go/pkg/mod/github.com/asticode/go-astiav@v0.2.0/buffersink_flag.go:4:10: fatal error: libavfilter/buffersink.h: No such file or directory
    4 | //#include <libavfilter/buffersink.h>
      |          ^~~~~~~~~~~~~~~~~~~~~~~~~~
compilation terminated.

**Comment by asticode** [comment]
I've got a few questions:

1) which version of ffmpeg did you install ?
2) how did you install it ?
3) could you share the output of `ls -l <your ffmpeg install path>/include/libavfilter`

**Comment by aungmoewin** [comment]
> I've got a few questions:
> 
> 1. which version of ffmpeg did you install ?
> 2. how did you install it ?
> 3. could you share the output of `ls -l <your ffmpeg install path>/include/libavfilter`

1. n4.4.1
2. `make install-ffmpeg` as your instruction
3. avfilter.h  buffersink.h  buffersrc.h  version.h

**Comment by aungmoewin** [comment]
I find that it is linker issue.  When I install libavfilter-dev `sudo apt install -y libavfilter-dev` and compile, it works.
