### ISSUE TITLE
ffmpeg 7.1

### ISSUE THREAD

**Issue by oldma3095** [asticode/go-astiav#106]
I try to use ffmpeg 7.1, has a error:
`The encoder timebase is not set`
![image](https://github.com/user-attachments/assets/5ce0d0f5-965c-4837-8f35-4c77d0f1feb7)

![image](https://github.com/user-attachments/assets/83b7bb5d-eb86-4ea7-a88a-533cfbd21b4b)

But ffmpeg 7.0 is ok.
astiav can support 7.1?

**Comment by asticode** [comment]
`go-astiav` officially only supports `ffmpeg` `n7.0` but in reality it should support `n7.1` as well.

The error you're getting is pretty weird: can you print the value of `astiav.NewRational(1, tr.VideoParams.FPS)` you're providing `tr.VideoTransStream.EncodeCtx.SetTimeBase()` at the top of your screenshot?

**Comment by voxeljorge** [comment]
The transcode example works for me with `n7.1` fwiw

**Comment by oldma3095** [comment]
> Reference i

![image](https://github.com/user-attachments/assets/81570933-f3de-41cb-b22b-eaa8b3e137a5)

ubuntu 22.04
https://github.com/BtbN/FFmpeg-Builds/releases/download/latest/ffmpeg-n6.1-latest-linux64-gpl-shared-6.1.tar.xz

**Comment by asticode** [comment]
Can you change ffmpeg log level to debug and share the output logs when you're experiencing the error?

**Comment by oldma3095** [comment]
> Can you change ffmpeg log level to debug and share the output logs when you're experiencing the error?

2024/11/25 16:51:30 No default whitelist set
2024/11/25 16:51:30 Original list of addresses:
2024/11/25 16:51:30 Address 127.0.0.1 port 554
2024/11/25 16:51:30 Interleaved list of addresses:
2024/11/25 16:51:30 Address 127.0.0.1 port 554
2024/11/25 16:51:30 Starting connection attempt to 127.0.0.1 port 554
2024/11/25 16:51:30 Successfully connected to 127.0.0.1 port 554
2024/11/25 16:51:30 SDP:
v=0
o=- 0 0 IN IP4 0.0.0.0
s=Streamed by oulec=IN IP4 0.0.0.0
t=0 0
a=range:npt=now-
a=control:*
m=video 0 RTP/AVP 96
b=AS:1944
a=fmtp:96 packetization-mode=1; profile-level-id=64001F; sprop-parameter-sets=Z2QAH6wkhAFAFuwEQAAAAwBAAAAMI8YMkg==,aO4yyLA=
a=rtpmap:96 H264/90000
a=control:trackID=0
m=audio 0 RTP/AVP 97
b=AS:122
a=fmtp:97 streamtype=5;profile-level-id=1;mode=AAC-hbr;sizelength=13;indexlength=3;indexdeltalength=3;config=1210
a=rtpmap:97 mpeg4-generic/44100/2
a=control:trackID=1
2024/11/25 16:51:30 video codec set to: h264
2024/11/25 16:51:30 RTP Packetization Mode: 1
2024/11/25 16:51:30 RTP Profile IDC: 64 Profile IOP: 0 Level: 1f
2024/11/25 16:51:30 Extradata set to 0x1db0950 (size: 38)
2024/11/25 16:51:30 audio codec set to: aac
2024/11/25 16:51:30 audio samplerate set to: 44100
2024/11/25 16:51:30 audio channels set to: 2
2024/11/25 16:51:30 setting jitter buffer size to 0
2024/11/25 16:51:30 setting jitter buffer size to 0
2024/11/25 16:51:30 hello state=0
2024/11/25 16:51:30 Failed to parse interval end specification ''
2024/11/25 16:51:30 nal_unit_type: 7(SPS), nal_ref_idc: 3
2024/11/25 16:51:30 nal_unit_type: 8(PPS), nal_ref_idc: 3
2024/11/25 16:51:30 Decoding VUI
2024/11/25 16:51:30 Transform tree:
2024/11/25 16:51:30 mdct_inv_float_avx2 - type: mdct_float, len: 64, factors[2]: [2, any], flags: [aligned, out_of_place, inv_only]
2024/11/25 16:51:30 fft32_asm_float_fma3 - type: fft_float, len: 32, factor: 2, flags: [aligned, inplace, out_of_place, preshuf, asm_call]
2024/11/25 16:51:30 Transform tree:
2024/11/25 16:51:30 mdct_inv_float_avx2 - type: mdct_float, len: 64, factors[2]: [2, any], flags: [aligned, out_of_place, inv_only]
2024/11/25 16:51:30 fft32_asm_float_fma3 - type: fft_float, len: 32, factor: 2, flags: [aligned, inplace, out_of_place, preshuf, asm_call]
2024/11/25 16:51:30 Transform tree:
2024/11/25 16:51:30 mdct_pfa_3xM_inv_float_c - type: mdct_float, len: 96, factors[2]: [3, any], flags: [unaligned, out_of_place, inv_only]
2024/11/25 16:51:30 fft16_ns_float_fma3 - type: fft_float, len: 16, factor: 2, flags: [aligned, inplace, out_of_place, preshuf]
2024/11/25 16:51:30 Transform tree:
2024/11/25 16:51:30 mdct_inv_float_avx2 - type: mdct_float, len: 120, factors[2]: [2, any], flags: [aligned, out_of_place, inv_only]
2024/11/25 16:51:30 fft_pfa_15xM_asm_float_avx2 - type: fft_float, len: 60, factors[2]: [15, 2], flags: [aligned, inplace, out_of_place, preshuf, asm_call]
2024/11/25 16:51:30 fft4_fwd_asm_float_sse2 - type: fft_float, len: 4, factor: 2, flags: [aligned, inplace, out_of_place, preshuf, asm_call]
2024/11/25 16:51:30 Transform tree:
2024/11/25 16:51:30 mdct_inv_float_avx2 - type: mdct_float, len: 128, factors[2]: [2, any], flags: [aligned, out_of_place, inv_only]
2024/11/25 16:51:30 fft_sr_asm_float_fma3 - type: fft_float, len: 64, factor: 2, flags: [aligned, inplace, out_of_place, preshuf, asm_call]
2024/11/25 16:51:30 Transform tree:
2024/11/25 16:51:30 mdct_inv_float_avx2 - type: mdct_float, len: 480, factors[2]: [2, any], flags: [aligned, out_of_place, inv_only]
2024/11/25 16:51:30 fft_pfa_15xM_asm_float_avx2 - type: fft_float, len: 240, factors[2]: [15, 2], flags: [aligned, inplace, out_of_place, preshuf, asm_call]
2024/11/25 16:51:30 fft16_asm_float_fma3 - type: fft_float, len: 16, factor: 2, flags: [aligned, inplace, out_of_place, preshuf, asm_call]
2024/11/25 16:51:30 Transform tree:
2024/11/25 16:51:30 mdct_inv_float_avx2 - type: mdct_float, len: 512, factors[2]: [2, any], flags: [aligned, out_of_place, inv_only]
2024/11/25 16:51:30 fft_sr_asm_float_fma3 - type: fft_float, len: 256, factor: 2, flags: [aligned, inplace, out_of_place, preshuf, asm_call]
2024/11/25 16:51:30 Transform tree:
2024/11/25 16:51:30 mdct_pfa_3xM_inv_float_c - type: mdct_float, len: 768, factors[2]: [3, any], flags: [unaligned, out_of_place, inv_only]
2024/11/25 16:51:30 fft_sr_ns_float_fma3 - type: fft_float, len: 128, factor: 2, flags: [aligned, inplace, out_of_place, preshuf]
2024/11/25 16:51:30 Transform tree:
2024/11/25 16:51:30 mdct_inv_float_avx2 - type: mdct_float, len: 960, factors[2]: [2, any], flags: [aligned, out_of_place, inv_only]
2024/11/25 16:51:30 fft_pfa_15xM_asm_float_avx2 - type: fft_float, len: 480, factors[2]: [15, 2], flags: [aligned, inplace, out_of_place, preshuf, asm_call]
2024/11/25 16:51:30 fft32_asm_float_fma3 - type: fft_float, len: 32, factor: 2, flags: [aligned, inplace, out_of_place, preshuf, asm_call]
2024/11/25 16:51:30 Transform tree:
2024/11/25 16:51:30 mdct_inv_float_avx2 - type: mdct_float, len: 1024, factors[2]: [2, any], flags: [aligned, out_of_place, inv_only]
2024/11/25 16:51:30 fft_sr_asm_float_fma3 - type: fft_float, len: 512, factor: 2, flags: [aligned, inplace, out_of_place, preshuf, asm_call]
2024/11/25 16:51:30 Transform tree:
2024/11/25 16:51:30 mdct_fwd_float_c - type: mdct_float, len: 1024, factors[2]: [2, any], flags: [unaligned, out_of_place, fwd_only]
2024/11/25 16:51:30 fft_sr_ns_float_fma3 - type: fft_float, len: 512, factor: 2, flags: [aligned, inplace, out_of_place, preshuf]
2024/11/25 16:51:30 nal_unit_type: 7(SPS), nal_ref_idc: 3
2024/11/25 16:51:30 nal_unit_type: 8(PPS), nal_ref_idc: 3
2024/11/25 16:51:30 Decoding VUI
2024/11/25 16:51:30 Decoding VUI
2024/11/25 16:51:30 nal_unit_type: 7(SPS), nal_ref_idc: 3
2024/11/25 16:51:30 nal_unit_type: 8(PPS), nal_ref_idc: 3
2024/11/25 16:51:30 nal_unit_type: 5(IDR), nal_ref_idc: 3
2024/11/25 16:51:30 Decoding VUI
2024/11/25 16:51:30 Format yuv420p chosen by get_format().
2024/11/25 16:51:30 Reinit context to 1280x720, pix_fmt: yuv420p
2024/11/25 16:51:30 nal_unit_type: 1(Coded slice of a non-IDR picture), nal_ref_idc: 2
2024/11/25 16:51:30 nal_unit_type: 1(Coded slice of a non-IDR picture), nal_ref_idc: 2
2024/11/25 16:51:30 nal_unit_type: 1(Coded slice of a non-IDR picture), nal_ref_idc: 2
2024/11/25 16:51:30 nal_unit_type: 1(Coded slice of a non-IDR picture), nal_ref_idc: 2
2024/11/25 16:51:30 nal_unit_type: 1(Coded slice of a non-IDR picture), nal_ref_idc: 2
2024/11/25 16:51:30 nal_unit_type: 1(Coded slice of a non-IDR picture), nal_ref_idc: 2
2024/11/25 16:51:30 first_dts -123680 not matching first dts NOPTS (pts NOPTS, duration 3750) in the queue
2024/11/25 16:51:30 All info found
2024/11/25 16:51:30 rfps: 23.416667 0.019616
2024/11/25 16:51:30 rfps: 23.500000 0.014414
2024/11/25 16:51:30 rfps: 23.583333 0.010014
2024/11/25 16:51:30 rfps: 23.666667 0.006416
2024/11/25 16:51:30 rfps: 23.666667 0.006416
2024/11/25 16:51:30 rfps: 23.750000 0.003620
2024/11/25 16:51:30 rfps: 23.750000 0.003620
2024/11/25 16:51:30 rfps: 23.833333 0.001625
2024/11/25 16:51:30 rfps: 23.833333 0.001625
2024/11/25 16:51:30 rfps: 23.916667 0.000432
2024/11/25 16:51:30 rfps: 23.916667 0.000432
2024/11/25 16:51:30 rfps: 24.000000 0.000041
2024/11/25 16:51:30 rfps: 24.000000 0.000041
2024/11/25 16:51:30 rfps: 24.083333 0.000452
2024/11/25 16:51:30 rfps: 24.083333 0.000452
2024/11/25 16:51:30 rfps: 24.166667 0.001665
2024/11/25 16:51:30 rfps: 24.166667 0.001665
2024/11/25 16:51:30 rfps: 24.250000 0.003680
2024/11/25 16:51:30 rfps: 24.250000 0.003680
2024/11/25 16:51:30 rfps: 24.333333 0.006496
2024/11/25 16:51:30 rfps: 24.333333 0.006496
2024/11/25 16:51:30 rfps: 24.416667 0.010114
2024/11/25 16:51:30 rfps: 24.500000 0.014534
2024/11/25 16:51:30 rfps: 24.583333 0.019756
2024/11/25 16:51:30 rfps: 48.000000 0.000166
2024/11/25 16:51:30 rfps: 48.000000 0.000166
2024/11/25 16:51:30 rfps: 120.000000 0.001036
2024/11/25 16:51:30 rfps: 120.000000 0.001036
2024/11/25 16:51:30 rfps: 240.000000 0.004144
2024/11/25 16:51:30 rfps: 240.000000 0.004144
2024/11/25 16:51:30 rfps: 23.976024 0.000072
2024/11/25 16:51:30 rfps: 23.976024 0.000072
2024/11/25 16:51:30 rfps: 47.952048 0.000287
2024/11/25 16:51:30 rfps: 47.952048 0.000287
2024/11/25 16:51:30 nal_unit_type: 7(SPS), nal_ref_idc: 3
2024/11/25 16:51:30 nal_unit_type: 8(PPS), nal_ref_idc: 3
2024/11/25 16:51:30 Decoding VUI
2024/11/25 16:51:30 Transform tree:
2024/11/25 16:51:30 mdct_inv_float_avx2 - type: mdct_float, len: 64, factors[2]: [2, any], flags: [aligned, out_of_place, inv_only]
2024/11/25 16:51:30 fft32_asm_float_fma3 - type: fft_float, len: 32, factor: 2, flags: [aligned, inplace, out_of_place, preshuf, asm_call]
2024/11/25 16:51:30 Transform tree:
2024/11/25 16:51:30 mdct_inv_float_avx2 - type: mdct_float, len: 64, factors[2]: [2, any], flags: [aligned, out_of_place, inv_only]
2024/11/25 16:51:30 fft32_asm_float_fma3 - type: fft_float, len: 32, factor: 2, flags: [aligned, inplace, out_of_place, preshuf, asm_call]
2024/11/25 16:51:30 Transform tree:
2024/11/25 16:51:30 mdct_pfa_3xM_inv_float_c - type: mdct_float, len: 96, factors[2]: [3, any], flags: [unaligned, out_of_place, inv_only]
2024/11/25 16:51:30 fft16_ns_float_fma3 - type: fft_float, len: 16, factor: 2, flags: [aligned, inplace, out_of_place, preshuf]
2024/11/25 16:51:30 Transform tree:
2024/11/25 16:51:30 mdct_inv_float_avx2 - type: mdct_float, len: 120, factors[2]: [2, any], flags: [aligned, out_of_place, inv_only]
2024/11/25 16:51:30 fft_pfa_15xM_asm_float_avx2 - type: fft_float, len: 60, factors[2]: [15, 2], flags: [aligned, inplace, out_of_place, preshuf, asm_call]
2024/11/25 16:51:30 fft4_fwd_asm_float_sse2 - type: fft_float, len: 4, factor: 2, flags: [aligned, inplace, out_of_place, preshuf, asm_call]
2024/11/25 16:51:30 Transform tree:
2024/11/25 16:51:30 mdct_inv_float_avx2 - type: mdct_float, len: 128, factors[2]: [2, any], flags: [aligned, out_of_place, inv_only]
2024/11/25 16:51:30 fft_sr_asm_float_fma3 - type: fft_float, len: 64, factor: 2, flags: [aligned, inplace, out_of_place, preshuf, asm_call]
2024/11/25 16:51:30 Transform tree:
2024/11/25 16:51:30 mdct_inv_float_avx2 - type: mdct_float, len: 480, factors[2]: [2, any], flags: [aligned, out_of_place, inv_only]
2024/11/25 16:51:30 fft_pfa_15xM_asm_float_avx2 - type: fft_float, len: 240, factors[2]: [15, 2], flags: [aligned, inplace, out_of_place, preshuf, asm_call]
2024/11/25 16:51:30 fft16_asm_float_fma3 - type: fft_float, len: 16, factor: 2, flags: [aligned, inplace, out_of_place, preshuf, asm_call]
2024/11/25 16:51:30 Transform tree:
2024/11/25 16:51:30 mdct_inv_float_avx2 - type: mdct_float, len: 512, factors[2]: [2, any], flags: [aligned, out_of_place, inv_only]
2024/11/25 16:51:30 fft_sr_asm_float_fma3 - type: fft_float, len: 256, factor: 2, flags: [aligned, inplace, out_of_place, preshuf, asm_call]
2024/11/25 16:51:30 Transform tree:
2024/11/25 16:51:30 mdct_pfa_3xM_inv_float_c - type: mdct_float, len: 768, factors[2]: [3, any], flags: [unaligned, out_of_place, inv_only]
2024/11/25 16:51:30 fft_sr_ns_float_fma3 - type: fft_float, len: 128, factor: 2, flags: [aligned, inplace, out_of_place, preshuf]
2024/11/25 16:51:30 Transform tree:
2024/11/25 16:51:30 mdct_inv_float_avx2 - type: mdct_float, len: 960, factors[2]: [2, any], flags: [aligned, out_of_place, inv_only]
2024/11/25 16:51:30 fft_pfa_15xM_asm_float_avx2 - type: fft_float, len: 480, factors[2]: [15, 2], flags: [aligned, inplace, out_of_place, preshuf, asm_call]
2024/11/25 16:51:30 fft32_asm_float_fma3 - type: fft_float, len: 32, factor: 2, flags: [aligned, inplace, out_of_place, preshuf, asm_call]
2024/11/25 16:51:30 Transform tree:
2024/11/25 16:51:30 mdct_inv_float_avx2 - type: mdct_float, len: 1024, factors[2]: [2, any], flags: [aligned, out_of_place, inv_only]
2024/11/25 16:51:30 fft_sr_asm_float_fma3 - type: fft_float, len: 512, factor: 2, flags: [aligned, inplace, out_of_place, preshuf, asm_call]
2024/11/25 16:51:30 Transform tree:
2024/11/25 16:51:30 mdct_fwd_float_c - type: mdct_float, len: 1024, factors[2]: [2, any], flags: [unaligned, out_of_place, fwd_only]
2024/11/25 16:51:30 fft_sr_ns_float_fma3 - type: fft_float, len: 512, factor: 2, flags: [aligned, inplace, out_of_place, preshuf]
2024/11/25 16:51:30 The encoder timebase is not set.
SIGSEGV: segmentation violation
PC=0x7b1986ea53fe m=0 sigcode=128 addr=0x0
signal arrived during cgo execution


this is my logs

**Comment by asticode** [comment]
I'll be honest I don't think there's anything wrong with `go-astiav` if your code works in `n7.0` and if the transcode example works in `n7.1` 🤔  Can you try with the `n7.2-dev` ffmpeg tag or with an upgraded version of `libx264`?

**Comment by asticode** [comment]
I'll close this issue for now but feel free to reopen it with your results from testing with `n7.2-dev` or with additional info that would help resolving the issue 👍
