### ISSUE TITLE
av_opt_set

### ISSUE THREAD

**Issue by oldma3095** [asticode/go-astiav#117]
codecContext and outputFormatContext need set priv_data's options.
example:
codecContext                     av_opt_set(codecContext->priv_data, "preset", "ultrafast", 0)
outputFormatContext        av_opt_set(outputFormatContext->priv_data, "pkt_size", "1316", 0)

**Comment by asticode** [comment]
I had already began working on something similar, I'll try to finish it 👍

**Comment by asticode** [comment]
fyi I've pushed on `master` the following:

- you can get `.PrivateData()` on both `*FormatContext` and `*CodecContext`
- you can get `.Options()` on `*PrivateData`
- you can `.List()`, `.Get()` and `.Set()` on `*Options`

Does that fix your issue?

**Comment by oldma3095** [comment]
![image](https://github.com/user-attachments/assets/c7c3fb6a-b672-453e-a3de-531274dc5171)
![image](https://github.com/user-attachments/assets/e2b66b64-5de8-4be0-a427-cafd11a0b1a6)
test by encode context set priv_data,it can work.
Thanks!
