### ISSUE TITLE
pleas add OutputCodecParameters to BitStreamFilterContext 

### ISSUE THREAD

**Issue by Cacsjep** [asticode/go-astiav#123]
to access converterd/filterd extradata after using a bitstream filter, OutputCodecParameters is needed

_mp4 -> annexb -> outputcodecparams extradata holds sps/pps_ in annex b

bit_stream_filter_context.go
```go
// https://ffmpeg.org/doxygen/7.0/structAVBSFContext.html#ab58f8c37eec197e0f30d17d60959a60d
func (bsfc *BitStreamFilterContext) OutputCodecParameters() *CodecParameters {
	return newCodecParametersFromC(bsfc.c.par_out)
}
```
thank u

**Comment by asticode** [comment]
I've added it in `master` 👍 

Can you confirm it fixes your issue?

**Comment by Cacsjep** [comment]
perfect as always, thank you very much
