### ISSUE TITLE
[Qustion] How to decode raw h264 stream?

### ISSUE THREAD

**Issue by nnnpa31** [asticode/go-astiav#13]
I'm trying to write a go implementation of a [scrcpy client](https://github.com/Genymobile/scrcpy) where the [scrcpy server](https://github.com/Genymobile/scrcpy/tree/master/server) sends a series of raw h264 data (nalu) to the socket connector. In the [official C implementation](https://github.com/Genymobile/scrcpy/blob/master/app/src/demuxer.c), they do this by using ffmpeg to decode the NALU packets in memory. Since my C skills are poor, I can't convert their code to a Go implementation, so some advice, help or examples would be appreciated.

Also: any thoughts on opening a "discussion" section in the repository? It would help to have a proper place for help questions like this.

Thanks :)

**Comment by asticode** [comment]
> I'm trying to write a go implementation of a [scrcpy client](https://github.com/Genymobile/scrcpy) where the [scrcpy server](https://github.com/Genymobile/scrcpy/tree/master/server) sends a series of raw h264 data (nalu) to the socket connector. In the [official C implementation](https://github.com/Genymobile/scrcpy/blob/master/app/src/demuxer.c), they do this by using ffmpeg to decode the NALU packets in memory. Since my C skills are poor, I can't convert their code to a Go implementation, so some advice, help or examples would be appreciated.

You could start by checking the [demuxing_decoding](https://github.com/asticode/go-astiav/blob/master/examples/demuxing_decoding/main.go) example and replace `is.CodecParameters().CodecID()` with `astiav.CodecIDH264` [here](https://github.com/asticode/go-astiav/blob/master/examples/demuxing_decoding/main.go#L78). There might be other things to change, but that should be good start 👍 

> Also: any thoughts on opening a "discussion" section in the repository? It would help to have a proper place for help questions like this.

You're right! I've created the discussions area 👍

**Comment by Tryanks** [comment]
> You could start by checking the [demuxing_decoding](https://github.com/asticode/go-astiav/blob/master/examples/demuxing_decoding/main.go) example and replace `is.CodecParameters().CodecID()` with `astiav.CodecIDH264` [here](https://github.com/asticode/go-astiav/blob/master/examples/demuxing_decoding/main.go#L78). There might be other things to change, but that should be good start 👍

Thanks, I will try and keep this issue open until I solve my needs and attach my solution here.
(I used the wrong account when asking this question, sorry)

**Comment by kfatehi** [comment]
Hi. I had a similar need, although I am decoding HEVC (which arrives over 0mq within a capnproto container). The advice from @asticode helped a lot. I want to mention that I spent a lot of time fighting with goav first, but it was a breeze with go-astiav and the referenced example.

My code at this point in time with successful decoding routine is linked here, maybe it will help you out @Tryanks https://github.com/comma-hacks/webrtc/blob/f06088234fa29e1aa06a077f5189a5814139cb4b/main.go

**Comment by Tryanks** [comment]
> Hi. I had a similar need, although I am decoding HEVC (which arrives over 0mq within a capnproto container). The advice from @asticode helped a lot. I want to mention that I spent a lot of time fighting with goav first, but it was a breeze with go-astiav and the referenced example.
> 
> My code at this point in time with successful decoding routine is linked here, maybe it will help you out @Tryanks https://github.com/comma-hacks/webrtc/blob/f06088234fa29e1aa06a077f5189a5814139cb4b/main.go

Thanks! It was very helpful for me, I only needed to replace the CodecID and I successfully decoded the bare stream.
I noticed that to wrap the bare data as AVPacket, I need to call the pkt.FromData method, my next step is to encode the decoded AVFrame as MJPEG and provide the bare stream, does it mean I can call the pkt.Data() method of the re-encoded AVPacket to achieve my purpose?

**Comment by asticode** [comment]
> my next step is to encode the decoded AVFrame as MJPEG and provide the bare stream, does it mean I can call the pkt.Data() method of the re-encoded AVPacket to achieve my purpose?

Take a look [this function](https://github.com/asticode/go-astiav/blob/master/examples/transcoding/main.go#L473) of the `transcoding` example, it specifically takes an input frame, encodes it as a packet and muxes the packet into a file.

Let me know if you're still having issues.

**Comment by nnnpa31** [comment]
I took care of everything! Decode, encode, reuse ......
Now the rest of my work is to finish go-scrcpy and to organize all the solutions and write a simple guide.
Thanks for all the help along the way!
