### ISSUE TITLE
Support for bitstream filtering

### ISSUE THREAD

**Issue by mihailj** [asticode/go-astiav#17]
Hello,

1st of all the project is a great step forward from the outdated `goav` bindings, really clean and easy to use.

I couldn't find any way to use bitstream filtering (for example `hevc_mp4toannexb`).

Am I missing something or it's not implemented yet?

Thanks,
Mihail

**Comment by asticode** [comment]
Thanks a lot for the kind words ❤️ 

Bitstream filtering is not implemented yet. That would mean adding some of [those functions](https://ffmpeg.org/doxygen/trunk/bsf_8h.html)(doc is out of date, but that's to give an idea).

**Comment by asticode** [comment]
FYI bitstream filtering support has now been added with https://github.com/asticode/go-astiav/commit/d8844951c9786ed203c545581dacb5e9a8c448d6 in `master` 👍
