### ISSUE TITLE
[example request] hardware accelerated en/decoding and tee example

### ISSUE THREAD

**Issue by c1ngular** [asticode/go-astiav#18]
Tee example exhibits the powerfulness of ffmpeg(probably go way of doing this ?) , hardware acceleration is very common nowadays , could you add those examples ?

Thanks

**Comment by asticode** [comment]
Could you link to those C examples if they already exist?

Hardware acceleration would indeed be a nice addition 👍

**Comment by c1ngular** [comment]
@asticode i could not find a C example of Tee other than this one : [https://ffmpeg.org/doxygen/2.8/tee_8c_source.html](https://ffmpeg.org/doxygen/2.8/tee_8c_source.html) , seems outdated  though.

**Comment by caseybarker** [comment]
Here's the hardware decoder example:
https://github.com/FFmpeg/FFmpeg/blob/master/doc/examples/hw_decode.c

Looks like we'd need support some of the stuff in `libavutil/hwcontext.h` and also `AVCodecHWConfig`.

**Comment by asticode** [comment]
FYI an hardware decoding example is now available [here](https://github.com/asticode/go-astiav/blob/master/examples/hardware_decoding/main.go) 👍
