### ISSUE TITLE
Embed ffmpeg binary 

### ISSUE THREAD

**Issue by Grogdunn** [asticode/go-astiav#20]
Hi, there is a way to embed ffmpeg in golang binary, so I can ship a single file with all included.

Thanks

**Comment by gedw99** [comment]
you can.

there are various packages out there for golang that do it.

then extract on startup.

**Comment by asticode** [comment]
> Hi, there is a way to embed ffmpeg in golang binary, so I can ship a single file with all included.
> 
> Thanks

If I were you, I'd use the standard library [embed](https://pkg.go.dev/embed) feature 👍

**Comment by c1ngular** [comment]
It may be treated and blocked as malware by some antivirus softwares ? @Grogdunn

**Comment by Grogdunn** [comment]
@c1ngular dunno, but when I have some spare time I'll give a try

**Comment by gedw99** [comment]
you can also download it on the fly.

**Comment by onthegit** [comment]
Why would you include the binary when the bindings link to the lib files?

**Comment by gedw99** [comment]
> It may be treated and blocked as malware by some antivirus softwares ? @Grogdunn

you have to sign it with your app.
