### ISSUE TITLE
cannot use _Ctype_ulong(len(b)) (value of type _Ctype_ulong) as type _Ctype_ulonglong in variable declaration

### ISSUE THREAD

**Issue by 491467928** [asticode/go-astiav#21]
when I run the simple,error happened：
# github.com/asticode/go-astiav
..\..\channel_layout.go:96:103: cannot use _Ctype_ulong(len(b)) (value of type _Ctype_ulong) as type _Ctype_ulonglong in variable declaration
..\..\dictionary.go:65:43: cannot use size (variable of type *_Ctype_ulong) as type *_Ctype_ulonglong in variable declaration
..\..\dictionary.go:71:52: cannot use size (variable of type _Ctype_ulong) as type _Ctype_ulonglong in variable declaration
..\..\frame.go:97:54: cannot use &linesize[0] (value of type *_Ctype_long) as type *_Ctype_longlong in variable declaration
..\..\frame.go:161:120: cannot use _Ctype_ulong(size) (value of type _Ctype_ulong) as type _Ctype_ulonglong in variable declaration
..\..\frame_side_data.go:25:11: cannot use d.c.size (variable of type _Ctype_ulonglong) as type _Ctype_ulong in assignment
..\..\packet.go:91:75: cannot use size (variable of type *_Ctype_ulong) as type *_Ctype_ulonglong in variable declaration
..\..\stream.go:61:75: cannot use size (variable of type *_Ctype_ulong) as type *_Ctype_ulonglong in variable declaration

go 1.19.3
ffmepg：5.1.2
astiav ：0.10.0

**Comment by asticode** [comment]
Mmm that's a weird one 🤔 

Which OS are you using and is your machine 32 or 64bits? 🤔

**Comment by 491467928** [comment]
win10 ，amd64

**Comment by lcsin** [comment]
when I run example/transcoding/main.go, the same error occurred.

**Comment by asticode** [comment]
FYI I've finally managed to reproduce the error using Github actions and I've pushed a fix in master.

I've also created a `v0.11.0` tag 👍
