### ISSUE TITLE
[Feature Request] Add ToImage method to the Frame struct.

### ISSUE THREAD

**Issue by nnnpa31** [asticode/go-astiav#22]
As the title. Add `ToImage` method to generate go's `image.Image` via AVFrame.
Just like gocv does.

**Comment by nnnpa31** [comment]
I have looked at #4 and see why this proposal is not feasible for now.

**Comment by asticode** [comment]
FYI [Frame.Data()](https://github.com/asticode/go-astiav/blob/master/frame.go#L57) now returns a [*FrameData](https://github.com/asticode/go-astiav/blob/master/frame_data.go#L12) that allows to either get data as `[]byte` or, if it's an image, get data as an `image.Image`.
