### ISSUE TITLE
Example on streaming h264

### ISSUE THREAD

**Issue by onthegit** [asticode/go-astiav#23]
Thanks for the project.

Is it possible to directly feed h264 chunks instead of reading from file?

Purpose is to mux h264 into mp4 file. h264 chunks coming from https://github.com/pion/webrtc

**Comment by asticode** [comment]
> Is it possible to directly feed h264 chunks instead of reading from file?

Sure, check out [this comment](https://github.com/asticode/go-astiav/issues/13#issuecomment-1418675963). It basically allows you to demux raw video frames and do whatever you want with frames afterwards, like remuxing them into an mp4 file in your case.

Let me know if that answers your question.

**Comment by onthegit** [comment]
Thank you for your reply. Quick question. From  the official ffmpeg compilation page they say that nasm and yasm need to be included for performance reasons. For the bindings are they required/included?
Thanks.

**Comment by asticode** [comment]
Can you link to that documentation?

The bindings only use the ffmpeg you have installed, they don't include any external lib. They're only required if the way you use the bindings require nasm or yasm.

**Comment by onthegit** [comment]
Hello,
here is the link:
https://trac.ffmpeg.org/wiki/CompilationGuide/Centos

I tried to make install-ffmpeg and it complained that nasm/yasm is not installed so I had to compile the from source. My os did not have nasm/yasm. Maybe your OS has them already and did not complain.

**Comment by asticode** [comment]
Ha ok, that's a dependency you need to build ffmpeg. This is not link to these bindings 👍
