### ISSUE TITLE
fatal error: libavfilter/buffersink.h: No such file or directory

### ISSUE THREAD

**Issue by onthegit** [asticode/go-astiav#24]
Hello,
I am using vscode for editor.  But the go language server is complaining that it can not find libavfilter/buffersink.h
/buffersink_flag.go:4:10: fatal error: libavfilter/buffersink.h: No such file or directory

settings.json:
```json
{
  "go.toolsEnvVars": {
    "CGO_ENABLED": "1",
    "CGO_LDFLAGS": "-L${workspaceFolder}/tmp/n5.1.2/lib",
    "CGO_CXXFLAGS": "-I${workspaceFolder}/tmp/n5.1.2/include",
    "PKG_CONFIG_PATH": "${workspaceFolder}/tmp/n5.1.2/lib/pkgconfig",
  },
}
```
The files are there in tmp/n5.1.2/include/
```
 ls tmp/n5.1.2/include/
libavcodec   libavfilter  libavutil    libswresample
libavdevice  libavformat  libpostproc  libswscale

ls tmp/n5.1.2/include/libavfilter/
avfilter.h    buffersrc.h  version_major.h
buffersink.h  version.h
```

**Comment by onthegit** [comment]
If I directly specify:
#include "./tmp/n5.1.2/include/libavfilter/buffersink.h"

it works, but that is not the solution.
Help?

**Comment by onthegit** [comment]
I managed to get it working by setting up a custom pkgconfig in bash script that set the PKG_CONFIG_PATH to the path in tmp. I don't know if it is the right way but it works:
```json
{
  "go.toolsEnvVars": {
    "CGO_ENABLED": "1",
    "CGO_LDFLAGS": "-L${workspaceFolder}/tmp/n5.1.2/lib",
    "CGO_CXXFLAGS": "-I${workspaceFolder}/tmp/n5.1.2/include",
    "PKG_CONFIG": "${workspaceFolder}/pkgconfig",
  },
}
```
I also modified libavfilter.pc for the correct directories

**Comment by onthegit** [comment]
PKG_CONFIG_PATH in go.toolsEnvVars did not have effect.

**Comment by asticode** [comment]
What if you use `CGO_CFLAGS` instead of `CGO_CXXFLAGS` in your first configuration?

**Comment by onthegit** [comment]
@asticode Does not work. The problem is pkg-config not finding the the config. I could not find a way to set PKG_CONFIG_PATH in vscode for go tools (for intellisense) except by manually overriding the pkgconfig PKG_CONFIG (binary) that exports PKG_CONFIG_PATH

**Comment by onthegit** [comment]
the pkgconfig bash script in my workspace folder is:
```bash
#!/bin/bash
export PKG_CONFIG_PATH=/home/user/dev/golang/go-astiav/tmp/n5.1.2/lib/pkgconfig
/usr/bin/pkg-config "$@"
```
