### ISSUE TITLE
m1 mac error 

### ISSUE THREAD

**Issue by ivanlebron** [asticode/go-astiav#28]
# github.com/asticode/go-astiav
./codec_context_flag.go:38:50: could not determine kind of name for C.AV_CODEC_FLAG2_DROP_FRAME_TIMECODE
./codec_context_flag.go:21:51: could not determine kind of name for C.AV_CODEC_FLAG_TRUNCATED

**Comment by asticode** [comment]
Which ffmpeg version are you using ?

**Comment by ivanlebron** [comment]
5.1.2

**Comment by ivanlebron** [comment]
fix

**Comment by asticode** [comment]
> fix

How did you do to fix your issue?
