### ISSUE TITLE
Implementation of Frame.Data() is not correct for all pixel formats

### ISSUE THREAD

**Issue by chmgr** [asticode/go-astiav#4]
Thanks for the great work you have done with this library!

I tried to use the Frame.Data() method to copy the raw image data of a YUV420P stream and the program sometimes crashed with "unexpected fault address" (segmentation violation).

I tracked the problem down to the algorithm of the Frame.Data method:

```go
func (f *Frame) Data() [NumDataPointers][]byte {
	b := [NumDataPointers][]byte{}
	for i := 0; i < int(NumDataPointers); i++ {
		b[i] = bytesFromC(func(size *C.int) *C.uint8_t {
			*size = f.c.linesize[i]
			if f.c.height > 0 {
				*size = *size * f.c.height
			} else if f.c.channels > 0 {
				*size = *size * f.c.channels
			}
			return f.c.data[i]
		})
	}
	return b
}
```

The YUV420P data consists of three planes. E.g. a 640x480 pixel frame, the planes have the following dimensions:

Y: 640x480
U: 320x240
V: 320x240

However, the implementation always multiplies the `linesize` of the plane with the image height which results in too much bytes being read from C. In the best case, the read image data contains garbage after the correct values, in the worst case, the program tries to read invalid memory addresses.

The AVPixFmtDescriptor struct describes the correct sizes for each plane. However the implementation is much more complicated...

So I would suggest to implement a simple function to receive the raw data of images as simple byte slice:

```go
func (f *Frame) GetImageBuffer() ([]byte, error) {

	// retrieve the image buffer size
	bufferSize := C.av_image_get_buffer_size(C.enum_AVPixelFormat(f.c.format), f.c.width, f.c.height, 1)
	if bufferSize < 0 {
		return nil, newError(bufferSize)
	}

	// create a buffer and copy the raw image data into it
	buffer := make([]byte, int(bufferSize))
	n := C.av_image_copy_to_buffer((*C.uint8_t)(unsafe.Pointer(&buffer[0])), bufferSize, (**C.uint8_t)(unsafe.Pointer(&f.c.data)), (*C.int)(unsafe.Pointer(&f.c.linesize)), C.enum_AVPixelFormat(f.c.format), f.c.width, f.c.height, 1)
	if n < 0 {
		return nil, newError(n)
	}

	return buffer, nil
}
```

That method does not output multidimensional slices as `Data()` does and only works for images. I don't submit a pull request so far - maybe you want the `Data()` method to be fixed (which I don't have capacity for know). If you feel that my implementation of `GetImageBuffer()` is useful, I would kindly submit a PR.

Best regards!

**Comment by asticode** [comment]
Thanks for describing the problem so clearly 👍  To be honest, I've never trusted my implementation of `Frame.Data()`. However, I think this is best if it is fixed. If you don't feel like it, no problem. However you seem to have investigated it a good bit so maybe you could point me in the right direction : could you elaborate on `The AVPixFmtDescriptor struct describes the correct sizes for each plane. However the implementation is much more complicated...`? What would need to be done exactly?

As for your needs, I would be open to a PR that adds the 2 following functions:

- `Frame.ImageBufferSize() int`
- `Frame.CopyImageToBuffer(size int) ([]byte, error)`

Additionnaly, do you know a function that would copy a buffer to an image ? 🤔

**Comment by chmgr** [comment]
I think the implementation of [`av_image_copy_to_buffer`](https://ffmpeg.org/doxygen/trunk/imgutils_8c_source.html#l00501) is a good reference to fix the `Data()` method: 

It uses `av_pix_fmt_desc_get` (line 509) to get information about the pixel format, then determines the number of components and extracts the raw data without padding (starting at line 523).

If you mean a function to create an `image.Image`, I don't know a library which supports various formats. For my use case with YUV420P format I use the following algorithm:

```go
buffer, _ := frame.GetImageBuffer()

w := frame.Width()
h := frame.Height()

img := &image.YCbCr{
	Y:              buffer[:w*h],
	Cb:             buffer[w*h : w*h+(w*h)/4],
	Cr:             buffer[w*h+(w*h)/4:],
	YStride:        frame.Linesize()[0],
	CStride:        frame.Linesize()[1],
	SubsampleRatio: image.YCbCrSubsampleRatio420,
	Rect:           image.Rect(0, 0, w, h),
}
```

However one would have to adapt it for all the formats one would like to support...

**Comment by asticode** [comment]
Thanks for taking the time to share that information 👍 

Regarding your needs, I've thought about it a little bit more, and I think that would be a better idea to add only one function `Frame.DataBytes() ([]byte, error)` that would be simplified to something along the lines of:

```go
if f.Height() > 0 && f.Width() > 0 {
  // TODO Get image buffer size
  // TODO Copy image to buffer
} else {
  return nil, errors.New("astiav: not implemented")
}
```

If you come up with a better solution than `f.Height() > 0 && f.Width() > 0` to identify the frame as an image, I'm open to it. An alternative would be to provide the `CodecContext` or `CodecParameter` to the function to retrieve the `MediaType` but I'd rather keep the function signature simple.

**Comment by chmgr** [comment]
Using dimensions to detect video frames seams OK to me. The [documentation](https://libav.org/documentation/doxygen/master/structAVFrame.html) states that these fields are video only, so this should be fine and a simple solution.

**Comment by asticode** [comment]
FYI [Frame.Data()](https://github.com/asticode/go-astiav/blob/master/frame.go#L57) now returns a [*FrameData](https://github.com/asticode/go-astiav/blob/master/frame_data.go#L12) that allows to either get data as `[]byte` or, if it's an image, get data as an `image.Image`.

I'll close this issue
