### ISSUE TITLE
AVFormatContext::interrupt_callback

### ISSUE THREAD

**Issue by jikard0** [asticode/go-astiav#51]
Is there binging for AVFormatContext::interrupt_callback and how can be used.

Thanks

**Comment by asticode** [comment]
You can use [this method](https://github.com/asticode/go-astiav/blob/master/format_context.go#L87) to set an interrupt callback on your `FormatContext`. All you need to do then is call `.Interrupt()` on the returned object whenever you want to trigger the interruption.

FYI I've revamped this part this morning, therefore you'll need to use the latest `master` or the `v0.13.0` tag to have this. Previously the method still existed but was not very developer friendly.

**Comment by asticode** [comment]
I'll close this issue but let know whether you still have questions 👍
