### ISSUE TITLE
Unexpected segfault error using astiav.FrameData .ToImage()

### ISSUE THREAD

**Issue by Valkhes** [asticode/go-astiav#64]
Hello, I'm encountering an issue with the lib, but I'm still unsure yet if it's because I'm missing a check on my side or if there is an issue with the lib.

My usecase is to retrieve frames from an H264 socket in order for me to retrieve a JPEG image at the end. (see this discussion we had 2 months ago : https://github.com/asticode/go-astiav/discussions/62 )

It has been working pretty well, but in some case I encounter a segfault.
What I can say about my usecase if it helps is that it's retrieving frames from a phone, meaning that the image can rotate over time. I'm having a feeling it could be linked, yet I'm not completely sure. ( Width x height -> height x width for the image size)

Here is a piece of the code, that we have been discussing before : 

```

        var decCodec *astiav.Codec
	var decCodecContext *astiav.CodecContext

	if decCodec = astiav.FindDecoder(astiav.CodecIDH264); decCodec == nil {
                 //print error
		return
	}

	if decCodecContext = astiav.AllocCodecContext(decCodec); decCodecContext == nil {
		//print error
		return
	}
	defer decCodecContext.Free()

	if err := decCodecContext.Open(decCodec, nil); err != nil {
		//print error
		return
	}

	pkt := astiav.AllocPacket()
	defer pkt.Free()

	f := astiav.AllocFrame()
	defer f.Free()

	inputFormatContext := astiav.AllocFormatContext()
	defer inputFormatContext.Free()

	ioContext, err := astiav.AllocIOContext(0x10000, false, c.Conn.Read, nil, nil)
	if err != nil {
		//print error
		return
	}
	defer ioContext.Free()

	inputFormatContext.SetPb(ioContext)

	inputFormat := astiav.FindInputFormat("h264")
	if inputFormat == nil {
		//print error
		return
	}

	if err := inputFormatContext.OpenInput("", inputFormat, nil); err != nil {
		//print error
		return
	}
	defer inputFormatContext.CloseInput()

	//Read frames

	for {
		select {
		case <-Stop:
			//stopping h264 processing
			return
		default:
			f.Unref()
			pkt.Unref()
			if err := inputFormatContext.ReadFrame(pkt); err != nil {
				//print error
		                 return
			}

			// Send packet
			if err := decCodecContext.SendPacket(pkt); err != nil {
				//print error
		                 return
			}
			// Receive frame
			if err := decCodecContext.ReceiveFrame(f); err != nil {
				//print error
		                 return
			}

			image, err := f.Data().GuessImageFormat()
			if err != nil {
				//print error
		                 return
			}

			err = f.Data().ToImage(image)
			if err != nil {
				//print error
		                 return
			}

			var buf bytes.Buffer
			err = jpeg.Encode(&buf, image, nil)
			if err != nil {
				//print error
		                 return
			}

...

```

Sometimes, I'm having a segfault at this point in the code : 

```
err = f.Data().ToImage(image)
if err != nil {
    //print error
    return
}
```

Here is the stacktrace : 

```
unexpected fault address 0x7f7bf6fd2000
fatal error: fault
[signal SIGSEGV: segmentation violation code=0x1 addr=0x7f7bf6fd2000 pc=0x108b20a39]

goroutine 127 gp=0xc0005036c0 m=5 mp=0xc000100008 [running]:
runtime.throw({0x10938f193?, 0x101011e88b0?})
	/usr/local/Cellar/go/1.22.4/libexec/src/runtime/panic.go:1023 +0x5c fp=0xc0011e8860 sp=0xc0011e8830 pc=0x108ae973c
runtime.sigpanic()
	/usr/local/Cellar/go/1.22.4/libexec/src/runtime/signal_unix.go:895 +0x285 fp=0xc0011e88c0 sp=0xc0011e8860 pc=0x108b01525
runtime.memmove()
	/usr/local/Cellar/go/1.22.4/libexec/src/runtime/memmove_amd64.s:427 +0x4f9 fp=0xc0011e88c8 sp=0xc0011e88c0 pc=0x108b20a39
runtime.gobytes(0x7f7bf6f29000, 0x151800)
	/usr/local/Cellar/go/1.22.4/libexec/src/runtime/string.go:309 +0x65 fp=0xc0011e8910 sp=0xc0011e88c8 pc=0x108b07105
github.com/asticode/go-astiav._Cfunc_GoBytes(...)
	_cgo_gotypes.go:2197
github.com/asticode/go-astiav.bytesFromC.func1(0x7f7bf6f29000, 0x108ab682b?)
	/Users/valkhes/go/pkg/mod/github.com/asticode/go-astiav@v0.15.0/bytes.go:30 +0x3e fp=0xc0011e8948 sp=0xc0011e8910 pc=0x109293cde
github.com/asticode/go-astiav.bytesFromC(0xc0011e8978)
	/Users/valkhes/go/pkg/mod/github.com/asticode/go-astiav@v0.15.0/bytes.go:30 +0x38 fp=0xc0011e8970 sp=0xc0011e8948 pc=0x109293c78
github.com/asticode/go-astiav.(*frameDataFrame).planeBytes(0xc000614028?, 0x2?)
	/Users/valkhes/go/pkg/mod/github.com/asticode/go-astiav@v0.15.0/frame_data.go:199 +0x3d fp=0xc0011e89a0 sp=0xc0011e8970 pc=0x10929c8bd
github.com/asticode/go-astiav.(*FrameData).toImageYCbCr(0xc0011e8e80, 0xc00022a380, 0xc00022a398, 0xc00022a3b0, 0xc00022a3c8, 0xc00022a3d0, 0xc00022a3d8, 0xc00022a3e0)
	/Users/valkhes/go/pkg/mod/github.com/asticode/go-astiav@v0.15.0/frame_data.go:116 +0xcb fp=0xc0011e89c8 sp=0xc0011e89a0 pc=0x10929c12b
github.com/asticode/go-astiav.(*FrameData).ToImage(0xc0011e8e90?, {0x109753130?, 0xc00022a380?})
	/Users/valkhes/go/pkg/mod/github.com/asticode/go-astiav@v0.15.0/frame_data.go:161 +0x18a fp=0xc0011e8a28 sp=0xc0011e89c8 pc=0x10929c54a

```

By any chance, do you have an idea about what can be happening here ? 
Any way to have more information about the issue, maybe a way to check if my incoming frame is corrupted, or a check I have been missing ? 

Thanks a lot !

**Comment by Valkhes** [comment]
Adding some info I forgot : 

go-astiav is in v0.15.0
I'm using go 1.22

**Comment by asticode** [comment]
Indeed it looks like it could be linked to the size of the frame changing 🤔  Basically, the problem is that the size computed [here](https://github.com/asticode/go-astiav/blob/master/frame_data.go#L200) is incorrect, and therefore when "transferring" the C bytes slice to Go [here](https://github.com/asticode/go-astiav/blob/master/bytes.go#L30), it segfaults.

Could you try logging `f.Height()`, `f.Width()` and `f.Linesize()` just before doing `f.Data().ToImage(image)` to see if indeed there's a size change before the segfault?

**Comment by Valkhes** [comment]
I'll do that asap today.
I suppose that what I can do is store the image size if it is the case, and as soon as it change, I can close everything and reopen everything so it's properly handled ?

**Comment by asticode** [comment]
Thing is normally the size change should be properly handled by your code since the frame is unrefed and you create a new FrameData struct everytime, my fear is that the decoder doesn't detect the frame size change 🤔

**Comment by Valkhes** [comment]
Something I forgot but which is an useful info : 

When it's going well (for exemple on my calculator app where I can not reproduce the issue), here is the logs : 

```
[info] 2024-07-31 03:07:16: changing from h: 2400, w: 1080, linesize: [1152 576 576 0 0 0 0 0] to h: 1080, w: 2400, linesize: [2432 1216 1216 0 0 0 0 0]
[info] 2024-07-31 03:07:16: size changed, trying to convert data to image
[info] 2024-07-31 03:07:16: succesfully converted data to image
[info] 2024-07-31 03:07:18: timeout while get buffer frame
[info] 2024-07-31 03:07:18: changing from h: 1080, w: 2400, linesize: [2432 1216 1216 0 0 0 0 0] to h: 2400, w: 1080, linesize: [1152 576 576 0 0 0 0 0]
[info] 2024-07-31 03:07:18: size changed, trying to convert data to image
[info] 2024-07-31 03:07:18: succesfully converted data to image
[info] 2024-07-31 03:07:19: changing from h: 2400, w: 1080, linesize: [1152 576 576 0 0 0 0 0] to h: 1080, w: 2400, linesize: [2432 1216 1216 0 0 0 0 0]
[info] 2024-07-31 03:07:19: size changed, trying to convert data to image
[info] 2024-07-31 03:07:19: succesfully converted data to image
[info] 2024-07-31 03:07:21: changing from h: 1080, w: 2400, linesize: [2432 1216 1216 0 0 0 0 0] to h: 2400, w: 1080, linesize: [1152 576 576 0 0 0 0 0]
[info] 2024-07-31 03:07:21: size changed, trying to convert data to image
[info] 2024-07-31 03:07:21: succesfully converted data to image
[info] 2024-07-31 03:07:22: changing from h: 2400, w: 1080, linesize: [1152 576 576 0 0 0 0 0] to h: 1080, w: 2400, linesize: [2432 1216 1216 0 0 0 0 0]
[info] 2024-07-31 03:07:22: size changed, trying to convert data to image
[info] 2024-07-31 03:07:22: succesfully converted data to image
[info] 2024-07-31 03:07:24: changing from h: 1080, w: 2400, linesize: [2432 1216 1216 0 0 0 0 0] to h: 2400, w: 1080, linesize: [1152 576 576 0 0 0 0 0]
[info] 2024-07-31 03:07:24: size changed, trying to convert data to image
[info] 2024-07-31 03:07:24: succesfully converted data to image
[info] 2024-07-31 03:07:25: changing from h: 2400, w: 1080, linesize: [1152 576 576 0 0 0 0 0] to h: 1080, w: 2400, linesize: [2432 1216 1216 0 0 0 0 0]
[info] 2024-07-31 03:07:25: size changed, trying to convert data to image
[info] 2024-07-31 03:07:25: succesfully converted data to image
[info] 2024-07-31 03:07:26: changing from h: 1080, w: 2400, linesize: [2432 1216 1216 0 0 0 0 0] to h: 2400, w: 1080, linesize: [1152 576 576 0 0 0 0 0]
[info] 2024-07-31 03:07:26: size changed, trying to convert data to image
[info] 2024-07-31 03:07:26: succesfully converted data to image

```

So the values are the same here when it's going well

**Comment by asticode** [comment]
Could you try replacing 
```go
image, err := f.Data().GuessImageFormat()
if err != nil {
    return
}

err = f.Data().ToImage(image)
if err != nil {
    return
}
```

with 

```go
_, err = f.Data().Bytes(1)
if err != nil {
    return
}
```

and let me know whether you still experience crashes? (you might need to change `.Bytes(1)` to `.Bytes(0)`, I don't remember which `align` value is correct)

**Comment by Valkhes** [comment]
By replacing as you said (and removing the jpeg.Encode() after because we don't get the image anymore), I don't have the crash. Doing .Bytes(1) works all the time.
I have a 100% reproductible way to get the issue now if when launching the code I have a running youtube video on my phone, so I'm sure it's not crashing with .Bytes(1).

I'm not sure if you have an idea with this info about the problem, I'm here for more tests if necessary, or for any workaround if you may know how to bypass this issue

**Comment by asticode** [comment]
Could you share an input stream that causes a crash? At that point, I need to be able to reproduce on my machine otherwise it won't be very effective.

You could replace `c.Conn.Read` in `ioContext, err := astiav.AllocIOContext(0x10000, false, c.Conn.Read, nil, nil)` with a function that writes the `[]byte` in a file as well, and share that file with me. The best would be to have this file as small as possible.

**Comment by Valkhes** [comment]
Hi, thanks again for your quick answers.

I have been running some tests this morning to confirm that the issue was only on my Intel mac and not on my ARM mac, and it was the case.
As I don't think the issue was in your code at this point (that would be strange), I realized that it could be because of ffmpeg@5 or some dependencies of ffmpeg.
I have been updating everything on my mac with brew and for the moment it seems it is working again. I'll come back after a day of testing to validate if everything is now fixed, but it may not be on your side.

**Comment by Valkhes** [comment]
Hello,

I think I was lucky at some point, because the problem is still here in fact.
In order to provide the file, I would need to wait next week as I'm not near the phone right now. It will be easier this way, otherwise I would have to provide a big file as it's not happening all the time if I'm not rotating the phone a lot.
I'll come back as soon as I have a file to provide.

Thanks again for all the help!

**Comment by Valkhes** [comment]
Hi, sorry for the delay.

I have been doing what you said, so know I am currently : 

- Launching the process on the phone to retrieve the H264 and launching the socket
- Using in `astiav.AllocIOContext()` a function that is reading the bytes and storing them in the file 
- Continuing the process of as before to retrieve the image

When it crashes, I have a file now with all the h264 bytes, so the last packet should be the one provoking the crash.

I have two files, one where I'm crashing straight from the beginning, and one where I'm crashing at a rotation. 
As I said before, I'm not reproducing on my ARM mac, only on my Intel one. I'm going to try to read these file with a pipeline, to see if I can reproduce the issue with FFMPEG or even gstreamer directly.

Here is a zip with the two videos : 

[videos.zip](https://github.com/user-attachments/files/16496086/videos.zip)

**Comment by Valkhes** [comment]
Funny thing, now that I have this "Invalid level prefix", I have been searching and realized there was this issue in screencopy (which is what we are using to get the frames from the phone) 

https://github.com/Genymobile/scrcpy/issues/347

It seems this is an error that happened because of the FFMPEG version...

**Comment by Valkhes** [comment]
The last test.
I opened both files provided on my Intel mac as input, and reproduced very easily the issue. For both files, if I launch it multiple time, they both have a chance to crash at the first frame, and the longest one is crashing all the time at the end otherwise. It shows there is a difference between both architecture here, as it seems it's being handled differently.

**Comment by asticode** [comment]
First off thanks for all the detailed information 👍 

I forgot to ask previously, but can you show me the part in your code that handles ffmpeg logs? Similar to [this](https://github.com/asticode/go-astiav/blob/master/examples/transcoding/main.go#L43)

**Comment by asticode** [comment]
FYI I'm reproducing the problem on an Intel MacOS with the following code and command:

```go
package main

import (
	"errors"
	"flag"
	"fmt"
	"log"
	"os"
	"strings"

	"github.com/asticode/go-astiav"
)

var (
	input = flag.String("i", "", "the input path")
)

func main() {
	astiav.SetLogLevel(astiav.LogLevelDebug)
	astiav.SetLogCallback(func(c astiav.Classer, l astiav.LogLevel, fmt, msg string) {
		var cs string
		if c != nil {
			if cl := c.Class(); cl != nil {
				cs = " - class: " + cl.String()
			}
		}
		log.Printf("ffmpeg log: %s%s - level: %d\n", strings.TrimSpace(msg), cs, l)
	})

	flag.Parse()

	if *input == "" {
		log.Println("Usage: <binary path> -i <input path>")
		return
	}

	decCodec := astiav.FindDecoder(astiav.CodecIDH264)
	if decCodec == nil {
		log.Fatal("main: decoder codec is nil")
	}

	decCodecContext := astiav.AllocCodecContext(decCodec)
	if decCodecContext == nil {
		log.Fatal("main: decoder codec context is nil")
	}
	defer decCodecContext.Free()

	if err := decCodecContext.Open(decCodec, nil); err != nil {
		log.Fatal(fmt.Errorf("main: opening decoder codec context failed: %w", err))
	}

	pkt := astiav.AllocPacket()
	defer pkt.Free()

	f := astiav.AllocFrame()
	defer f.Free()

	inputFormatContext := astiav.AllocFormatContext()
	defer inputFormatContext.Free()

	file, err := os.Open(*input)
	if err != nil {
		log.Fatal(fmt.Errorf("main: opening %s failed: %w", *input, err))
	}
	defer file.Close()

	ioContext, err := astiav.AllocIOContext(
		0x10000,
		false,
		func(b []byte) (n int, err error) {
			return file.Read(b)
		},
		nil,
		nil,
	)
	if err != nil {
		log.Fatal(fmt.Errorf("main: allocating io context failed: %w", err))
	}
	defer ioContext.Free()

	inputFormatContext.SetPb(ioContext)

	inputFormat := astiav.FindInputFormat("h264")
	if inputFormat == nil {
		log.Fatal("main: input format is nil")
	}

	if err := inputFormatContext.OpenInput("", inputFormat, nil); err != nil {
		log.Fatal(fmt.Errorf("main: opening input format failed: %w", err))
	}
	defer inputFormatContext.CloseInput()

	for {
		log.Println("main: reading frame")
		if err := inputFormatContext.ReadFrame(pkt); err != nil {
			if errors.Is(err, astiav.ErrEof) {
				break
			}
			log.Fatal(fmt.Errorf("main: reading frame failed: %w", err))
		}

		log.Println("main: sending packet")
		if err := decCodecContext.SendPacket(pkt); err != nil {
			log.Fatal(fmt.Errorf("main: sending packet failed: %w", err))
		}

		for {
			log.Println("main: receiving frame")
			if err := decCodecContext.ReceiveFrame(f); err != nil {
				if errors.Is(err, astiav.ErrEof) || errors.Is(err, astiav.ErrEagain) {
					break
				}
				log.Fatal(fmt.Errorf("main: receiving frame failed: %w", err))
			}

			log.Println("main: guessing image format")
			image, err := f.Data().GuessImageFormat()
			if err != nil {
				log.Fatal(fmt.Errorf("main: guessing image format failed: %w", err))
			}

			log.Println("main: to image")
			if err := f.Data().ToImage(image); err != nil {
				log.Fatal(fmt.Errorf("main: filling image with frame failed: %w", err))
			}

			log.Println("main: success")
		}
	}
}
```

```
$ go run main.go -i crash_first_frame.h264
```

**Comment by Valkhes** [comment]
Hello !

Sorry for the delay, I never set SetLogLevel() and SetLogCallback(), I realized I never used it, which may be a reason I missed some errors.

I'll try to add this tomorrow to the code, maybe I'll catch new errors. For the moment I was just printing returning errors from all the methods, but I suppose the log callback would help to retrieve ffmpeg internal errors toi.

**Comment by asticode** [comment]
I've pushed a fix on the `fix-segfault` branch (with it I'm not experiencing any segfaults locally anymore), would you mind testing your code with it and let me know whether you still experience segfaults?

**Comment by Valkhes** [comment]
Thanks, I'll be looking ASAP!

A bit in a struggle as I need to finish some things before the weekend, but it's definitively in my todo list. I'm coming back when I can to tell you if it is now fixed. (Also going to add the logs as we talked before)

**Comment by asticode** [comment]
No worries, I realized something was wrong and force pushed another fix a few minutes ago. I've removed the `fix-segfault` branch and rather pushed my fix on the `dev` branch 👍

**Comment by asticode** [comment]
FYI I've fixed all tests and have done further testing: all seems good therefore I've merged in `master`. However that would help if, when you have some time, you could confirm that it indeed fixes your issue 👍

**Comment by Valkhes** [comment]
Hello @asticode ! 

I've been running the files I sent you before with my code, it stopped crashing.
I've then launched the "real" program I have been using with the phone and made multiple rotation, nothing breaks anymore !

It seems your fix has been working succesfully.

Thanks a lot again for all the help and the quick answers !
