### ISSUE TITLE
No bindings for AVProgram in avformat

### ISSUE THREAD

**Issue by jikard0** [asticode/go-astiav#68]
Hello ,

I can find binding for AVStream but cannot find binding for AVProgram.
Very useful to manipulate ABR HLS and MPTS streams, filter by program number for example.

**Comment by asticode** [comment]
`AVProgram` is not implemented for now. Could you provide a list of methods/features you would need? I don't want to implement everything avformat provides but I don't want to miss on things you would need either 👍

**Comment by asticode** [comment]
For instance, would what I've added on the `dev` branch be enough for your use case?

**Comment by jikard0** [comment]
Working exactly as expected. Thank you so much.

**Comment by asticode** [comment]
Great, I've merged it into `master` 👍 

I'm closing this issue but feel free to reopen it or let me know whether you need a tag
