### ISSUE TITLE
Any possible to replace the input/output FormatContext to golang  []byte  for pure memory mod

### ISSUE THREAD

**Issue by hisunwei** [asticode/go-astiav#7]
I have a scene to extract aac audio stream from m3u8/ts  realtime  for a sppech-to-text model directly with write into file.

It's that possible to transcode the ts file to acc audio all in memory mod?

**Comment by asticode** [comment]
If your input is a ts stream available on network and the output you're looking for is raw audio samples, you can check [this example](https://github.com/asticode/go-astiav/tree/master/examples/transcoding). It basically reads an input, decodes frames, filters frames, encodes frames and muxes frames. What you'll need to extract from this example is reading the input, decoding frames and once you have the frame you can simply get thei `.Data()` as `[]byte`
