### ISSUE TITLE
AVFilterLink.frame_rate removed since 7.1

### ISSUE THREAD

**Issue by cpunion** [asticode/go-astiav#87]
See https://github.com/FFmpeg/FFmpeg/blob/n7.1/libavfilter/avfilter.h#L557C8-L557C20

../../.version-fox/temp/1729094400-53635/golang/packages/pkg/mod/github.com/asticode/go-astiav@v0.23.0/filter_link.go:32:30: l.c.frame_rate undefined (type *_Ctype_AVFilterLink has no field or method frame_rate)

See history: https://github.com/FFmpeg/FFmpeg/commits/n7.1/libavfilter/avfilter.h , it has more changes.

**Comment by asticode** [comment]
FYI I've made the necessary (breaking) changes so that `go-astiav` is compatible both with `n7.0` and `n7.1` 👍  It's available with version `v0.24.0`. Can you confirm this fixes your problem?

**Comment by asticode** [comment]
Great, I'll close the issue for now, but feel free to reopen it in case of problems 👍
