### ISSUE TITLE
How to build on windows with ffmpeg?

### ISSUE THREAD

**Issue by CypherpunkSamurai** [asticode/go-astiav#93]
Hello asticode,

I'm trying to use this library in my project and the project targets windows systems.
When I try to run go build it promted for pkg-config. I installed pkg-config using choco as evident from the build process in the [ci tests here](https://github.com/asticode/go-astiav/blob/master/.github/workflows/test.yml). I'm now stuck at it trying to find `libavcodec` and other libs.

Please help 🙏🏼

**Comment by asticode** [comment]
Can you share the command you're running and the error output you're getting?

**Comment by CypherpunkSamurai** [comment]
Hey @asticode,
Thanks for reply. I actually managed to compile it a few hours after the creating issue.

The make command is failing at applying the diff, also `diffutils` was missing in msys2 environment.

I have two questions.
1. can we opt for using the tar ball snapshot version from the releases then use normal `patch` from diffutils?
2. is it possible to create a section for install instructions? id be happy to help out with a PR for the README.

**Comment by CypherpunkSamurai** [comment]
> You mean modify the `Makefile`?

Somewhat, can we use tar balls from https://www.ffmpeg.org/releases/ffmpeg-7.1.tar.gz and then use basic `diff` and `patch` commands to patch it?

I kinda tried it, it's also pretty much faster than fetching the whole git repo.

> There's already an `install` section in the README, what do you feel is missing there?

I was wondering if we could have a windows specific note or subsection for each os if possible. Build steps on unix and darwin are pretty much same, on windows we can suggest the specific requirements.

**Comment by asticode** [comment]
> Somewhat, can we use tar balls from https://github.com/FFmpeg/FFmpeg/tarball/n7.0 and then use basic diff and patch commands to patch it?

I'm not looking to make this change in the `Makefile`, however you can use your own `Makefile` that uses the tar balls instead 👍 

> I was wondering if we could have a windows specific note or subsection for each os if possible. Build steps on unix and darwin are pretty much same, on windows we can suggest the specific requirements.

Sure, you can submit a PR and we can go from there 👍
