### ISSUE TITLE
out of memory when trying to stream 4k over rtc

### ISSUE THREAD

**Issue by CypherpunkSamurai** [asticode/go-astiav#97]
**Hello again, 👋🏼**
I'm trying to use this lib alongside pion to stream content over to a browser, however i'm running into memory leak issue. can you please kindly point out where i require to free / unref the memory?

## TLDR

Streaming 4K Over Pion RTC is giving me `cannot allocate memory` errors on calling `*astiav.CodecContext.SendFrame`

## Code

I'm using [ffmpeg-send pion/example-webrtc-applications](https://github.com/pion/example-webrtc-applications/) as a starting point for the app. I added a `defer scaledFrame.Unref()` before the send frame is called (`// Send frame to encoder`) however the issue still remains.

Here's my `stream.go` file:
```go
// Package main provides functionality for streaming H264 video over WebRTC
package main

import (
	"bufio"
	"encoding/base64"
	"encoding/json"
	"errors"
	"fmt"
	"io"
	"os"
	"strings"
	"time"

	"github.com/asticode/go-astiav"
	"github.com/pion/webrtc/v4"
	"github.com/pion/webrtc/v4/pkg/media"
)

// Global variables for managing video stream processing
// nolint: gochecknoglobals
var (
	// FormatContext for handling input video format
	inputFormatContext *astiav.FormatContext

	// Components for video decoding
	decodeCodecContext *astiav.CodecContext
	decodePacket       *astiav.Packet
	decodeFrame        *astiav.Frame
	videoStream        *astiav.Stream

	// Components for video scaling and encoding
	softwareScaleContext *astiav.SoftwareScaleContext
	scaledFrame          *astiav.Frame
	encodeCodecContext   *astiav.CodecContext
	encodePacket         *astiav.Packet

	pts int64 // Presentation timestamp
	err error
)

// Duration between H264 frames
const fps = 30
const h264FrameDuration = time.Second / fps

// Enum Resolutions
type Resolution string

const (
	Resolution240p  Resolution = "426x240"
	Resolution360p  Resolution = "640x360"
	Resolution480p  Resolution = "854x480"
	Resolution720p  Resolution = "1280x720"
	Resolution1080p Resolution = "1920x1080"
	Resolution2k    Resolution = "2048x1080"
	Resolution4k    Resolution = "3840x2160"
)

// writeH264ToTrack continuously reads frames from the input, processes them,// and writes H264 encoded video to the WebRTC track
func writeH264ToTrack(track *webrtc.TrackLocalStaticSample) {
	astiav.RegisterAllDevices()

	initTestSrc()
	defer freeVideoCoding()

	ticker := time.NewTicker(h264FrameDuration)
	for ; true; <-ticker.C {
		// Read frame from lavfi input
		if err = inputFormatContext.ReadFrame(decodePacket); err != nil {
			if errors.Is(err, astiav.ErrEof) {
				break
			}
			panic(err)
		}

		// Rescale timestamps to match codec timebase
		decodePacket.RescaleTs(videoStream.TimeBase(), decodeCodecContext.TimeBase())

		// Send packet to decoder
		if err = decodeCodecContext.SendPacket(decodePacket); err != nil {
			panic(err)
		}

		for {
			// Receive decoded frame
			if err = decodeCodecContext.ReceiveFrame(decodeFrame); err != nil {
				if errors.Is(err, astiav.ErrEof) || errors.Is(err, astiav.ErrEagain) {
					break
				}
				panic(err)
			}

			// Initialize video encoding on first frame
			initVideoEncoding()

			// Scale the frame to desired format
			if err = softwareScaleContext.ScaleFrame(decodeFrame, scaledFrame); err != nil {
				panic(err)
			}

			// Set presentation timestamp
			pts++
			scaledFrame.SetPts(pts)
			defer scaledFrame.Unref()

			// Send frame to encoder
			if err = encodeCodecContext.SendFrame(scaledFrame); err != nil {
				panic(err)
			}

			for {
				// Receive encoded packets
				encodePacket = astiav.AllocPacket()
				if err = encodeCodecContext.ReceivePacket(encodePacket); err != nil {
					if errors.Is(err, astiav.ErrEof) || errors.Is(err, astiav.ErrEagain) {
						break
					}
					panic(err)
				}

				// Write encoded H264 data to WebRTC track
				if err = track.WriteSample(media.Sample{Data: encodePacket.Data(), Duration: h264FrameDuration}); err != nil {
					panic(err)
				}
			}
		}
	}
}

// initTestSrc initializes the test video source and decoder
func initTestSrc() {
	if inputFormatContext = astiav.AllocFormatContext(); inputFormatContext == nil {
		panic("Failed to AllocCodecContext")
	}

	// Open test video source with specified parameters
	if err = inputFormatContext.OpenInput(fmt.Sprintf("testsrc=size=%s:rate=%d", Resolution4k, fps), astiav.FindInputFormat("lavfi"), nil); err != nil {
		panic(err)
	}
	// Get stream information from input
	if err = inputFormatContext.FindStreamInfo(nil); err != nil {
		panic(err)
	}

	videoStream = inputFormatContext.Streams()[0]

	// Set up decoder for video stream
	decodeCodec := astiav.FindDecoder(videoStream.CodecParameters().CodecID())
	if decodeCodec == nil {
		panic("FindDecoder returned nil")
	}

	if decodeCodecContext = astiav.AllocCodecContext(decodeCodec); decodeCodecContext == nil {
		panic(err)
	}

	// Copy codec parameters to context
	if err = videoStream.CodecParameters().ToCodecContext(decodeCodecContext); err != nil {
		panic(err)
	}

	decodeCodecContext.SetFramerate(inputFormatContext.GuessFrameRate(videoStream, nil))

	// Open decoder
	if err = decodeCodecContext.Open(decodeCodec, nil); err != nil {
		panic(err)
	}

	decodePacket = astiav.AllocPacket()
	decodeFrame = astiav.AllocFrame()
}

// initVideoEncoding initializes the H264 encoder and scaling context
func initVideoEncoding() {
	if encodeCodecContext != nil {
		return
	}

	// Find H264 encoder
	h264Encoder := astiav.FindEncoder(astiav.CodecIDH264)
	if h264Encoder == nil {
		panic("No H264 Encoder Found")
	}

	// Allocate encoder context
	if encodeCodecContext = astiav.AllocCodecContext(h264Encoder); encodeCodecContext == nil {
		panic("Failed to AllocCodecContext Decoder")
	}

	// Configure encoder parameters
	encodeCodecContext.SetPixelFormat(astiav.PixelFormatYuv420P)
	encodeCodecContext.SetSampleAspectRatio(decodeCodecContext.SampleAspectRatio())
	encodeCodecContext.SetTimeBase(astiav.NewRational(1, fps))
	encodeCodecContext.SetWidth(decodeCodecContext.Width())
	encodeCodecContext.SetHeight(decodeCodecContext.Height())

	// Open encoder
	if err = encodeCodecContext.Open(h264Encoder, nil); err != nil {
		panic(err)
	}

	// Create scaling context for format conversion
	softwareScaleContext, err = astiav.CreateSoftwareScaleContext(
		decodeCodecContext.Width(),
		decodeCodecContext.Height(),
		decodeCodecContext.PixelFormat(),
		decodeCodecContext.Width(),
		decodeCodecContext.Height(),
		astiav.PixelFormatYuv420P,
		astiav.NewSoftwareScaleContextFlags(astiav.SoftwareScaleContextFlagBilinear),
	)
	if err != nil {
		panic(err)
	}

	scaledFrame = astiav.AllocFrame()
}

// freeVideoCoding releases all allocated resources
func freeVideoCoding() {
	inputFormatContext.CloseInput()
	inputFormatContext.Free()

	decodeCodecContext.Free()
	decodePacket.Free()
	decodeFrame.Free()

	scaledFrame.Free()
	softwareScaleContext.Free()
	encodeCodecContext.Free()
	encodePacket.Free()
}

```

## Error

The stream is somehow a little glitchy and colors aren't appropriate in the gradient.

![image](https://github.com/user-attachments/assets/0f442d19-17ff-4cf6-8d0b-616e9aa00e8d)

Whenever I run this I get the following error after 30 sec of streaming to the browser:

```go
[h264_mf @ 000001d7e7bb6000] MFT name: 'H264 Encoder MFT'
Connection State has changed connected 
panic: Cannot allocate memory

goroutine 1 [running]:
main.writeH264ToTrack(0xc0000fcde0)
        B:/Code/go/rtc_screen/stream.go:108 +0x565
main.main()
        B:/Code/go/rtc_screen/main.go:75 +0x2cc
```

**Comment by asticode** [comment]
It seems you're using `defer scaledFrame.Unref()` to unref the frame used to receive the scaling output, but you're using it inside a `for` loop so it won't be called until the `for` loop is exited. Instead it should be called at the end of each loop. Otherwise the frame's internal buffer is never freed and that would explain the memory leak.

**Comment by CypherpunkSamurai** [comment]
Thank you for the help.

I made the changes as suggested, it still seems to be leaking memory yet again. The program terminates on 18th frame. also the gradient is having glitches. Its moving back and forth, and the numbers are flickering on change.

On a sidenote, can you explain to me what the ffmpeg workflow we are using here (im guessing were transcoding here?). I'm very new to ffmpeg lib functions, and would like to get to know how this pion ffmpeg streaming is implemented.

I want to implement this from scratch using go-astiav instead of tweaking the existing example. Also would like to use github.com/asticode/go-astikit for memory management rather than manual work.

**Comment by asticode** [comment]
> it still seems to be leaking memory yet again

Another thing that seems weird to me is that you shouldn't call `initVideoEncoding` in the `for` loop, its content should only be called once at the beginning, just like you do with `initTestSrc`. The only thing you can execute in the `for` loop is `astiav.CreateSoftwareScaleContext` since you need the `decodeCodecContext` here.

> can you explain to me what the ffmpeg workflow we are using here

You're using a bit of several things: decoding, scaling, encoding and muxing.

**Comment by CypherpunkSamurai** [comment]
> Another thing that seems weird to me is that you shouldn't call initVideoEncoding in the for loop, its content should only be called once at the beginning

I just copied it from the pion examples. It looks like it has major bugs.

As you can tell i clearly have no idea how ffmpeg lib works under the hood, but I'm slowly learning it thanks to this tutorial https://github.com/leandromoreira/ffmpeg-libav-tutorial.

> You're using a bit of several things: decoding, scaling, encoding and muxing.

Alright, let me go through the astiav examples and mix and match this. Will report back soon.

**Comment by asticode** [comment]
> I just copied it from the pion examples. It looks like it has major bugs.

Can you provide a link to those examples so that I provide a fix?

**Comment by CypherpunkSamurai** [comment]
Sure can 👍🏼

This `send-ffmpeg` example by Sean is the only one in the pion examples repository:
https://github.com/pion/example-webrtc-applications/tree/master/ffmpeg-send

**Comment by asticode** [comment]
Thanks for the link 👍 

FYI I was wrong in both my assumptions above, but I've managed to find fixes for both the memory leak and the glitches, and I've submitted a PR to pion's repository which you can take a look into to apply the fixes in your code as well: https://github.com/pion/example-webrtc-applications/pull/272/files

Let me know whether that fixes your issues 👍

**Comment by CypherpunkSamurai** [comment]
Thanks it works like charm! 😄

I'll keep exploring go-astiav, and ffmpeg.

Looking forward to using astiav in my future projects from now 🚀 way to go!

**Comment by asticode** [comment]
❤️
